name: ğŸš€ EC2 Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ§­ Checkout latest code
        uses: actions/checkout@v4

      - name: ğŸ—ï¸ Connect & Deploy to EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/devopslab-mini
            sudo rm -rf *
            git clone https://github.com/deekshithchowdoju/devopslab-mini.git temp
            cp -r temp/* .
            rm -rf temp
            sudo systemctl reload nginx
            echo "âœ… Deployment complete on $(hostname) at $(date)"
